In [2]:
#决策树
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, plot_tree

# Load data
iris = load_iris()

#划分训练集和测试集
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3)

#训练，预测
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
predict_target=clf.predict(x_test)

#预测结果与真实结果的对比
print(sum(predict_target==y_test))

#输出准确率，召回率，F值
print(metrics.classification_report(y_test,predict_target))
print(metrics.confusion_matrix(y_test, predict_target))

40
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.84      0.89      0.86        18
           2       0.83      0.77      0.80        13

    accuracy                           0.89        45
   macro avg       0.89      0.89      0.89        45
weighted avg       0.89      0.89      0.89        45

[[14  0  0]
 [ 0 16  2]
 [ 0  3 10]]


In [16]:
#决策树
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import datasets, ensemble

# Load data
iris = load_iris()

#划分训练集和测试集
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3)

#训练，预测
clf = ensemble.RandomForestClassifier(max_depth=3, n_estimators=5, max_features=3)
clf.fit(x_train,y_train)
predict_target=clf.predict(x_test)

#预测结果与真实结果的对比
print(sum(predict_target==y_test))

#输出准确率，召回率，F值
print(metrics.classification_report(y_test,predict_target))

40
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.92      0.75      0.83        16
           2       0.75      0.92      0.83        13

    accuracy                           0.89        45
   macro avg       0.89      0.89      0.89        45
weighted avg       0.90      0.89      0.89        45

